[package]
name = "vapor_keeb"
version = "0.1.0"
edition = "2021"

[dependencies]
ch32-hal = { path = "./ch32-hal", features = [
    "defmt",
    # "ch32v307vct6",
    "ch32v305rbt6",
    "embassy",
    "rt",
    # "highcode",
    "time-driver-tim1",
    "usb",
] }
embassy-executor = { version = "0.6.0", features = [
    "nightly",
    "integrated-timers",
    "arch-spin",
    "executor-thread",
] }
embassy-futures = "0.1.1"

critical-section = { version = "1.1.3" }
embassy-time = "0.3.2"
embassy-usb = { version = "0.3.0", features = [
    "defmt",
] }
embassy-usb-driver = "0.1.0"
nb = "1.1.0"

qingke-rt = "0.3"
qingke = "0.3"

panic-halt = "0.2.0"
embedded-hal-bus = "0.2.0"
defmt = "0.3"

[patch.crates-io]
qingke = { path = "./qingke" }
qingke-rt = { path = "./qingke/qingke-rt" }
embassy-executor = { path = "./embassy/embassy-executor" }
embassy-time-driver= { path = "./embassy/embassy-time-driver" }
embassy-time= { path = "./embassy/embassy-time" }

[profile.release]
debug = "full"
strip = false   # symbols are not flashed to the microcontroller, so don't strip them.
lto = true
opt-level = "z" # Optimize for size.
